[tools]
tuist = "4.203.4"

[env]
TUIST_OPENATTRIBUTEGRAPH_COMPUTE = "1"
OPENATTRIBUTEGRAPH_OPENATTRIBUTESHIMS_COMPUTE = "1"
OPENATTRIBUTEGRAPH_OPENATTRIBUTESHIMS_COMPUTE_BINARY = "0"
OPENATTRIBUTEGRAPH_OPENATTRIBUTESHIMS_COMPUTE_BINARY_VERSION = "0.5.2"
OPENATTRIBUTEGRAPH_OPENATTRIBUTESHIMS_COMPUTE_SOURCE_VERSION = "0.5.2"
