name: Compatibility tests 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compatibility_tests_macos:
    name: Execute compatibility tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            xcode-version: "15.3"   # Swift 5.10
    runs-on: ${{ matrix.os }}
    env:
      OPENGRAPH_WERROR: 1
      OPENGRAPH_SWIFT_TESTING: 1
      OPENGRAPH_ATTRIBUTEGRAPH: 1
      OPENGRAPH_COMPATIBILITY_TEST: 1
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Swift version
        run: swift --version
      - name: Run tests against Apple's AttributeGraph on macOS via SwiftPM
        run: |
          swift test \
            --build-path .build-compatibility-test-debug
      - name: Run tests against Apple's AttributeGraph on macOS via Xcode
        run: |
          xcodebuild test \
            -scheme OpenGraph-Package \
            -sdk macosx \
            -destination "platform=macOS" \
            -skipPackagePluginValidation \
            -skipMacroValidation