name: Wasm 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  wasmer_test:
    name: Execute tests on WASM
    strategy:
      fail-fast: false
      matrix:
        swift_version: ["5.10.0-RELEASE", "6.0-SNAPSHOT-2024-09-18-a"]
        os: [ubuntu-22.04]
        include:
          - swift_version: "6.0-SNAPSHOT-2024-09-18-a"
            continue-on-error: true
    runs-on: ${{ matrix.os }}
    env:
      OPENGRAPH_WERROR: 1
      OPENGRAPH_ATTRIBUTEGRAPH: 0
      OPENGRAPH_COMPATIBILITY_TEST: 0
    steps:
      - uses: actions/checkout@v4
      - uses: swiftwasm/setup-swiftwasm@v1
        with:
          swift-version: wasm-${{ matrix.swift_version }}
      - name: build
        continue-on-error: ${{ matrix.continue-on-error }}
        run: |
          swift build --triple wasm32-unknown-wasi
      # - name: test
      #   run: |
      #     swift test --triple wasm32-unknown-wasi