name: Wasm 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  wasmer_test:
    name: Execute tests on WASM
    strategy:
      fail-fast: false
      matrix:
        swift_version: ["5.10.0-RELEASE"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    env:
      OPENGRAPH_WERROR: 1
      OPENGRAPH_SWIFT_TESTING: 0
      OPENGRAPH_ATTRIBUTEGRAPH: 0
      OPENGRAPH_COMPATIBILITY_TEST: 0
    steps:
      - uses: actions/checkout@v4
      - uses: swiftwasm/setup-swiftwasm@v1
        with:
          swift-version: wasm-${{ matrix.swift_version }}
      - name: build
        run: |
          swift build --triple wasm32-unknown-wasi
      # Blocked by upstream support for WASM. See https://github.com/apple/swift-testing/issues/228
      # - name: test
        # run: |
          # swift test --triple wasm32-unknown-wasi
