name: XCFramework

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build_xcframework:
    name: Build XCFramework
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
        xcode-version: ["26.6"]   # Swift 6.3.3
    runs-on:
      - ${{ matrix.os }}
      - xcode-26.6
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Xcode
        uses: OpenSwiftUIProject/setup-xcode@v2
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Set up mise
        uses: jdx/mise-action@v2
        with:
          install: false
          cache: false
      - name: Set up Tuist cache
        run: |
          source Scripts/Tuist/common.sh
          tuist_ci_setup
        shell: bash
      - name: Build XCFramework
        run: ./Scripts/build_xcframework.sh
      - name: Upload XCFramework
        uses: actions/upload-artifact@v4
        with:
          name: OpenAttributeGraph.xcframework.zip
          path: .build/Xcode/Frameworks/OpenAttributeGraph.xcframework.zip
